### ISSUE TITLE
Queue App bind not target class

### ISSUE THREAD

**Issue by MgHtinLynn** [delenamalan/laravel-custom-http-mail-handler#1]
Using custom driver together with queue . The issue was found Target "Target class [mail.manager] does not exist.". 
I'm using queue database to send email with custom driver. How can I use with should queue at send mail ?

**Comment by deanmalan** [comment]
Hi @MgHtinLynn, could you share some of your code?

**Comment by le-bru** [comment]
I can confirm that the implemented approach doesn't work for queued emails.
To make it work, and simplify the code a little bit at the same time, you can get rid of the CustomMailManger and instead in the CustomMailServiceProvider, in the registerIlluminateMailer method, use this code instead:
`        parent::registerIlluminateMailer();

        $this->app['mail.manager']->extend('YOUR_DRIVER_NAME', function (array $config) {
            return new YOUR_TRANSPORT_CLASS();
        });`

Tested on Laravel 8.
